import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";
import Banner from "@/components/Banner";

import dynamic from "next/dynamic";
import { draftMode } from "next/headers";

import { token } from "@/sanity/lib/fetch";

const PreviewProvider = dynamic(() => import("@/components/PreviewProvider")); //? dynamic import to avoid SSR & avoid load

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-7xl mx-auto`}>
        <Header />
        <Banner />
        {draftMode().isEnabled ? (
          <PreviewProvider token={token}>{children}</PreviewProvider>
        ) : (
          children
        )}
      </body>
    </html>
  );
}
